desc "Run the tests and prepare for Danger"
lane :test do |options|

  # Const

  run_tests(
    project: "Tests-CI.xcodeproj", 
    scheme: "Tests-CI",
    derived_data_path: "temp/derived/",
    xcodebuild_formatter: "xcpretty -f `xcpretty-json-formatter`",
    code_coverage: true,
    devices: ["platform=iOS Simulator,name=iPhone 14 pro"]
  )
end
