desc "Run the tests and prepare for Danger"
lane :test do |options|

  # Const

  run_tests(
    project: "Tests-CI.xcodeproj", 
    scheme: "Tests-CI",
    target: "Tests-CI",
    derived_data_path: "temp/derived/",
    xcodebuild_formatter: "xcpretty -f `xcpretty-json-formatter`",
    code_coverage: true,
    devices: ["iPhone 14 Pro Max"],
    destination: "platform=iOS Simulator,id=72D088E1-E457-43F3-A481-8420294E4600",
  )
end
