name: Danger

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  Setup:
    permissions: write-all
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      
  Tests:
    permissions: write-all
    runs-on: macos-13
    needs: Setup

    steps:
      - name: Test Stage
        run: |
          bundle install
          bundle exec fastlane test

  Danger:
    permissions: write-all
    runs-on: macos-13
    needs: Tests

    steps:
      - name: Danger Stage
        run: |
          brew install danger/tap/danger-js
          swift build
          swift run danger-swift ci --verbose
          echo "Danger Lint stage complete."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}