name: Danger

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Danger Stage
        run: |
          swift build
          swift run danger-swift ci
          echo "Danger Lint stage complete."